site_name: LLMeter
copyright: Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
theme:
  name: material
  icon:
    annotation: material/plus-circle-outline
    repo: material/github
  logo: llmeter-sq-dark-192px.png
  favicon: favicon.svg
  font:
    text: Inter
    code:  Roboto Mono
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: llmeter-light
    toggle:
      icon: material/weather-night
      name: "Switch to dark mode"
  - media: "(prefers-color-scheme: dark)"
    scheme: llmeter-dark
    toggle:
      icon: material/weather-sunny
      name: "Switch to light mode"
  features:
    - header.autohide
    - content.code.copy
    - content.code.annotate
    - navigation.indexes
    - navigation.footer
    - navigation.top
    - navigation.tabs
nav:
  - User Guide:
    - index.md
    - Installation: user_guide/installation.md
    - Key Concepts: user_guide/key_concepts.md
    - Metrics and Statistics: user_guide/metrics.md
    - Connect to Endpoints: user_guide/connect_endpoints.md
    - Run Experiments: user_guide/run_experiments.md
  - API Reference:
    - reference/index.md
    - callbacks:
      - reference/callbacks/index.md
      - base: reference/callbacks/base.md
      - cost:
        - reference/callbacks/cost/index.md
        - dimensions: reference/callbacks/cost/dimensions.md
        - model: reference/callbacks/cost/model.md
        - providers:
          - reference/callbacks/cost/providers/index.md
          - sagemaker: reference/callbacks/cost/providers/sagemaker.md
        - results: reference/callbacks/cost/results.md
        - serde: reference/callbacks/cost/serde.md
      - mlflow: reference/callbacks/mlflow.md
    - endpoints:
      - reference/endpoints/index.md
      - base: reference/endpoints/base.md
      - bedrock: reference/endpoints/bedrock.md
      - bedrock_invoke: reference/endpoints/bedrock_invoke.md
      - litellm: reference/endpoints/litellm.md
      - openai: reference/endpoints/openai.md
      - sagemaker: reference/endpoints/sagemaker.md
    - experiments: reference/experiments.md
    - plotting:
      - reference/plotting/index.md
    - results: reference/results.md
    - runner: reference/runner.md
    - tokenizers: reference/tokenizers.md
    - prompt_utils: reference/prompt_utils.md
    - utils: reference/utils.md
repo_url: https://github.com/awslabs/llmeter
repo_name: awslabs/llmeter
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.snippets
  - attr_list
  - md_in_html
extra:
  generator: false
extra_css:
  - stylesheets/extra.css
plugins:
- search
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        options:
          docstring_style: google
          docstring_options:
            ignore_init_summary: true
          show_source: true
          show_root_heading: true
          show_root_full_path: false
          show_symbol_type_heading: true
          show_symbol_type_toc: true
          merge_init_into_class: true
          show_if_no_docstring: false
          signature_crossrefs: true
          separate_signature: true
