name: Publish docs
on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-python@v4
          with:
            python-version: 3.12
        - name: Install Poetry
          run: |
            curl -sSL https://install.python-poetry.org | python - -y
        - name: Install dependencies
          run: poetry install --sync --no-interaction --with docs
        - name: Deploy
          run: mkdocs gh-deploy --force
